# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0616de6b9561165ad281f074325d55949721537b8229c3ec694a92512474b35177ab4d951106d9021b2df65678fee49361c58bc2e41f7a98332517be70893736

test:
  secret_key_base: a83dc2eac95d253578bfe0aff3b90b7391baab415fcc2698dec2d1fe5ed321269843c50694285d72b03a87a87faee26cc0054480e015af6048131dc8c91860b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
